// numbat-managed plugin - do not edit
// Generated by `numbat hook install --agent opencode`; observe-only.
import { spawn } from "node:child_process";

const NUMBAT_BIN = "__NUMBAT_BIN__";
const EXTRA_ARGS = ["--installed-by=numbat", "--output=file", "--output-file", "__OUTPUT_FILE__"];

function forward(lifecycle, payload) {
  const child = spawn(NUMBAT_BIN, ["hook", lifecycle, "--agent", "opencode", ...EXTRA_ARGS], {
    stdio: ["pipe", "ignore", "ignore"],
  });
  child.stdin.write(JSON.stringify(payload));
  child.stdin.end();
}

export const NumbatPlugin = async ({ directory }) => {
  return {
    "tool.execute.before": async (input, output) => {
      forward("opencode-pre-tool", { directory, input, output });
    },
  };
};

export default NumbatPlugin;
