#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 3 ]]; then
  echo "usage: $0 VERSION ARM64_SHA256 AMD64_SHA256" >&2
  exit 2
fi

version="$1"
arm64_sha256="$2"
amd64_sha256="$3"

if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]; then
  echo "invalid version: $version" >&2
  exit 2
fi
if [[ ! "$arm64_sha256" =~ ^[0-9a-f]{64}$ ]]; then
  echo "invalid arm64 checksum" >&2
  exit 2
fi
if [[ ! "$amd64_sha256" =~ ^[0-9a-f]{64}$ ]]; then
  echo "invalid amd64 checksum" >&2
  exit 2
fi

cat <<FORMULA
# typed: false
# frozen_string_literal: true

# This file was generated by Sandy's release workflow. DO NOT EDIT.
require "download_strategy"
require "json"
require "utils/curl"

class SandyGitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
  def initialize(url, name, version, **meta)
    super
    match = url.match(%r{^https://github\.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(.+)$})
    raise CurlDownloadStrategyError, "unexpected release URL: #{url}" unless match

    @owner, @repo, @tag, @asset_name = match.captures
    @token = ENV["HOMEBREW_GITHUB_API_TOKEN"].to_s.strip
    odie <<~EOS if @token.empty?
      HOMEBREW_GITHUB_API_TOKEN is required while Sandy is distributed privately.

      Authenticate with GitHub CLI using an account with access to
      kontext-security/sandy, then retry:
        HOMEBREW_GITHUB_API_TOKEN="\$(gh auth token)" brew install kontext-security/tap/sandy
    EOS
  end

  private

  def _fetch(url:, resolved_url:, timeout:)
    curl_download "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}",
                  "--header", "Accept: application/octet-stream",
                  "--header", "Authorization: Bearer #{@token}",
                  to: temporary_path, timeout: timeout
  end

  def asset_id
    release = JSON.parse(Utils::Curl.curl_output(
      "--fail", "--silent", "--location",
      "--header", "Accept: application/vnd.github+json",
      "--header", "Authorization: Bearer #{@token}",
      "https://api.github.com/repos/#{@owner}/#{@repo}/releases/tags/#{@tag}"
    ).stdout)
    asset = release.fetch("assets", []).find { |candidate| candidate["name"] == @asset_name }
    odie "asset #{@asset_name} not found on #{@owner}/#{@repo} release #{@tag}" unless asset

    asset["id"]
  end
end

class Sandy < Formula
  desc "Native macOS sandboxing for AI coding agents"
  homepage "https://kontext.security"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kontext-security/sandy/releases/download/v$version/sandy_${version}_darwin_amd64.tar.gz",
          using: SandyGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "$amd64_sha256"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kontext-security/sandy/releases/download/v$version/sandy_${version}_darwin_arm64.tar.gz",
          using: SandyGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "$arm64_sha256"
    end
  end

  def install
    bin.install "sandy"
  end

  def caveats
    <<~EOS
      Sandy works independently of Kontext:
        sandy run -- claude

      Sandy is currently distributed from a private GitHub repository. Keep
      HOMEBREW_GITHUB_API_TOKEN available when installing or upgrading it.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sandy --version")
  end
end
FORMULA
