#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 3 ]]; then
  echo "usage: $0 VERSION ARM64_SHA256 AMD64_SHA256" >&2
  exit 2
fi

version="$1"
arm64_sha256="$2"
amd64_sha256="$3"

if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]; then
  echo "invalid version: $version" >&2
  exit 2
fi
if [[ ! "$arm64_sha256" =~ ^[0-9a-f]{64}$ ]]; then
  echo "invalid arm64 checksum" >&2
  exit 2
fi
if [[ ! "$amd64_sha256" =~ ^[0-9a-f]{64}$ ]]; then
  echo "invalid amd64 checksum" >&2
  exit 2
fi

cat <<FORMULA
# typed: false
# frozen_string_literal: true

# This file was generated by Sandy's release workflow. DO NOT EDIT.

class Sandy < Formula
  desc "Native macOS sandboxing for AI coding agents"
  homepage "https://kontext.security"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kontext-security/sandy/releases/download/v$version/sandy_${version}_darwin_amd64.tar.gz"
      sha256 "$amd64_sha256"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kontext-security/sandy/releases/download/v$version/sandy_${version}_darwin_arm64.tar.gz"
      sha256 "$arm64_sha256"
    end
  end

  def install
    bin.install "sandy"
  end

  def caveats
    <<~EOS
      Sandy works independently of Kontext:
        sandy run -- claude

      Verify that macOS sandboxing is available:
        sandy doctor
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sandy --version")
  end
end
FORMULA
